### ISSUE TITLE
支持提供数据源schema树形栏

### ISSUE THREAD

**Issue by oozkoo** [EdurtIO/incubator-datacap#106]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

能直观看到数据源中库表信息，不用每次都执行show tables

### Use Cases

null

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue
