### ISSUE TITLE
[Feature] Support for multiple result sets

### ISSUE THREAD

**Issue by ZhangZhaohai** [EdurtIO/incubator-datacap#133]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

创建A Tab，查出内容 AContext。
再创建B Tab，查出内容BContext。
再回到A Tab，结果栏出依旧显示BContext。需要重新执行A Tab脚本，才能再看到AContext。

### Expected behaviour

bug

### Actual behaviour

bug

### Steps to reproduce

1. 创建A Tab，查出内容 AContext。
2. 再创建B Tab，查出内容BContext。
3. 再回到A Tab，结果栏出依旧显示BContext。需要重新执行A Tab脚本，才能再看到AContext。

### Package versions

- Java: `java --version`
- Node: `node --version`
- Npm: `npm -v`
- Server: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`
- 1

### Configuration

```yaml
1
```

### System information

- Operating system: ...
- Browser: ...

**Comment by qianmoQ** [comment]
Stale issue message
