### ISSUE TITLE
[Web] [Editor] The 'keyword' is repeated with tab page addition

### ISSUE THREAD

**Issue by gouyehappy** [EdurtIO/incubator-datacap#208]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

The 'keyword' is repeated with tab page addition

### Expected behaviour

The keyword does not appear repeatedly

### Actual behaviour

The keyword is repeated

### Steps to reproduce

null

### Package versions

- Java: `java --version`
- Node: `node --version`
- Npm: `npm -v`
- Server: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`

### Configuration

```yaml
null
```

### System information

- Operating system: ...
- Browser: ...

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
Fixed on #283
