### ISSUE TITLE
Bug report on 设置MySQL数据源

### ISSUE THREAD

**Issue by ldbinac** [EdurtIO/incubator-datacap#304]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

设置MySQL数据源，“高级-数据库”字段必须带一个？结尾才可以正常设置成功，否则就设置失败，提示“unkown database xxxx”

### Expected behaviour

可以正常设置数据库

### Actual behaviour

设置MySQL数据源，“高级-数据库”字段必须带一个？结尾才可以正常设置成功，否则就设置失败，提示“unkown database xxxx”

### Steps to reproduce

数据源-选择MySQL数据库

### Package versions

- Java: JDK11

### Configuration

```yaml
系统配置
```

### System information

- Operating system: windows
- Browser: Microsoft Edge 111

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
@ldbinac 感谢提供相关信息，我们来复现并修复它
