### ISSUE TITLE
[Bug] Transmission of sensitive data in plain text

### ISSUE THREAD

**Issue by Lianghao-Chu** [EdurtIO/incubator-datacap#346]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

程序在进行登陆等操作时，将密码等敏感信息使用 HTTP 进行明文传输。攻击者
可以通过捕获网络流量利用该漏洞获取用户的密码并登录帐户。

### Expected behaviour

敏感数据在传输过程中应该以密文形式存在

### Actual behaviour

敏感数据在传输过程中以明文形式存在

### Steps to reproduce

以登陆界面为例
1.打开 Wireshark，截取 http 报文
2.在登陆界面输入演示账号与密码进行登录
3.找到登录发送的 POST 请求报文，查看负载信息即可获得数据

### Package versions

无

### Configuration

```yaml
无
```

### System information

- Operating system: Oracle VM VirtualBox 6.1：Seed-Ubuntu 20.04
- Browser: Firefox/83.0

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
Stale issue message
