### ISSUE TITLE
Feature  Support simultaneous submission of multiple SQL queries

### ISSUE THREAD

**Issue by zgpsuper888** [EdurtIO/incubator-datacap#383]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

rt

### Use Cases

   SELECT * FROM table_a  WHERE id = '215' ;

   SELECT * FROM table_b  WHERE a_id = 215 ;

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
Stale issue message
