### ISSUE TITLE
Feature ck query efficiency is very slow

### ISSUE THREAD

**Issue by ocean-zhc** [EdurtIO/incubator-datacap#396]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

clickhouse Query the same query sql statement
DataCap on Docker ：query time：3414ms，
CloudBeaver on Docker：query time：147ms

The guess is that the datacap front-end needs to render a large result set.

### Use Cases
``` sql
select
  *
from
  sjjsq_db.dwa_szh_cw_jx
```

### Screenshots / Mockups

<img width="703" alt="image" src="https://github.com/EdurtIO/datacap/assets/46189785/1611ea51-baae-4e78-848e-9ff217954712">
<img width="2194" alt="image" src="https://github.com/EdurtIO/datacap/assets/46189785/1952a5b5-28b6-4c1d-ae97-56064603686f">

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
The default value of CloudBeaver is 1000. datacap does not limit the number of CloudBeaver files

**Comment by ocean-zhc** [comment]
> The default value of CloudBeaver is 1000. datacap does not limit the number of CloudBeaver files

thx!  I'm OK!
