### ISSUE TITLE
使用过程中发现的几个问题

### ISSUE THREAD

**Issue by hophiya** [EdurtIO/incubator-datacap#411]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

你好，
工具体验很好，但也存在如下几个问题：
1.管理账号不能直接创建新用户，
2.管理账号不能关闭注册功能，而注册较为简单，是否存在风险？
3. 新注册账号默认拥有User权限，用户权限默认能进行数据查询等操作，有数据泄露风险
4. 数据查询权限要不开放，要不关闭，不能针对部分账号开放

### Use Cases

1.通过登录页面直接注册，但存在 2风险？
3通过去掉User的权限，新建权限并授权给需要用户
4.目前看无此功能，是否有解决方案？

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
感谢提交，我们会在后续完善权限这块的功能

Thanks for submitting, we will improve the function of the permission section in the future

**Comment by hophiya** [comment]
> 

感谢回复，期待后续版本更新

**Comment by qianmoQ** [comment]
Stale issue message
