### ISSUE TITLE
🐛 [Bug] [Query] - The sql editor cannot be opened

### ISSUE THREAD

**Issue by devhelperuu** [EdurtIO/incubator-datacap#464]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

浏览器：
版本：1.16.0
问题1：查询功能 - sql编辑器没有出现，无法编辑sql，去个人中心更新编辑器以后解决此问题
问题2：管理/历史 - 报错，删除`audit_plugin`表的`plugin_id=9`的数据后解决此问题

### Expected behaviour

fixbug

### Actual behaviour

null

### Steps to reproduce

1. 使用1.16.0版本
2. 新安装后第一次打开可复现

### Package versions

- datacap - 1.16.0

### Configuration

```yaml
null
```

### System information

- debian - 12
- java - 11
- chrome - 117.0.5938.92

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue
