### ISSUE TITLE
✨ [Feature] Some suggestions

### ISSUE THREAD

**Issue by meimosor** [EdurtIO/incubator-datacap#501]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/devlive-community/datacap/blob/dev/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

可以提供一些集成示例，来体现框架的功能强在哪儿，具体用到哪些场景，比如：
1. jpa/mybatis等相关的sdk集成示例。如何集成？
2. 需提供对连接器的说明。具体怎么用？如何扩展连接器
3. 多数据源的集成原理是如何实现的？动态切换数据源如何实现？以及多数据源下的分布式事务解决方案？

### Use Cases

暂无

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
1. 后续我们会增加使用 SDK 示例以及集成方式
2. 扩展连接器方式：https://datacap.edurt.io/developer_guide/plugin-java.html https://datacap.edurt.io/developer_guide/plugin-kotlin.html
3. 多数据源方式是基于 SPI 实现，当选择数据源后会根据插件类型动态获取，DataCap 默认不做任何事务相关操作，需要基于底层插件来支持

---

1. We will add SDK examples and integration methods in the future.
2. Extended connector method: https://datacap.edurt.io/developer_guide/plugin-java.html https://datacap.edurt.io/developer_guide/plugin-kotlin.html
3. The multi-data source method is implemented based on SPI. When the data source is selected, it will be dynamically obtained according to the plug-in type. DataCap does not perform any transaction-related operations by default and needs to be supported based on the underlying plug-in.
