### ISSUE TITLE
🐛 [Bug] Dashboard display incomplete

### ISSUE THREAD

**Issue by Smilewh888** [EdurtIO/incubator-datacap#555]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/devlive-community/datacap/blob/dev/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

<img width="527" alt="image" src="https://github.com/devlive-community/datacap/assets/75770940/a77a7738-7504-4b75-a66a-d2e128e92f1f">

### Expected behaviour

normal

### Actual behaviour

visualization

### Steps to reproduce

visualization

### Package versions

- Java: `java --version`
- Node: `node --version`
- Npm: `npm -v`
- Server: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`

### Configuration

```yaml
default
```

### System information

- Operating system: mac
- Browser:  chrom 120.0.6099.109

**Comment by qianmoQ** [comment]
Fixed on `V2` version
