### ISSUE TITLE
🚀 [Question] How is the pipeline used? 

### ISSUE THREAD

**Issue by Smilewh888** [EdurtIO/incubator-datacap#556]
![image](https://github.com/devlive-community/datacap/assets/75770940/ba1bda34-9e45-4ab5-b2c5-bed3f9b8563f)

![image](https://github.com/devlive-community/datacap/assets/75770940/9c26c2bd-9d28-4eac-8b7c-25101a649148)

![image](https://github.com/devlive-community/datacap/assets/75770940/7edf7e42-822d-4eb9-acee-de2009fd6d7e)

![image](https://github.com/devlive-community/datacap/assets/75770940/60f31f3a-8055-4370-bd8d-31724dfbe879)

我想把下面test_datacap数据库表的数据，同步另一个test_datacap_test库中，对于流水线的操作步骤是什么？
![image](https://github.com/devlive-community/datacap/assets/75770940/77aa1266-b504-4201-827f-b059cc6fb8c4)

**Comment by qianmoQ** [comment]
![image](https://github.com/devlive-community/datacap/assets/20521442/abcf123b-2451-4384-a674-d69bb3733416)
