### ISSUE TITLE
🦉 [Plugin] Support fs for tencent cos

### ISSUE THREAD

**Issue by devlivecommunity** [EdurtIO/incubator-datacap#636]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/devlive-community/datacap/blob/dev/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Affected Module

File System

### Plug-in website or document address

https://cloud.tencent.com/product/cos

**Comment by qianmoQ** [comment]
Stale issue message
