### ISSUE TITLE
Feature for support database write operation

### ISSUE THREAD

**Issue by lijing0293** [EdurtIO/incubator-datacap#70]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

-- 查看建库语句
show create database A
-- 删除数据库
drop database A

#
能支持以上操作就更完美了

### Use Cases

-- 查看建库语句
show create database A
-- 删除数据库
drop database A

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue
