### ISSUE TITLE
[Plugin] [Redis] Bug report Cannot init RedisConnection

### ISSUE THREAD

**Issue by GtoCm** [EdurtIO/incubator-datacap#71]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Cannot init RedisConnection `cannot init redisconnection` The account password is correctly configured

### Expected behaviour

You can use the Redis data source

### Actual behaviour

Not working

### Steps to reproduce

Add the Redis connection source configuration

### Package versions

- Java: `1.8`
- Node: `16`
- Npm: `7`
- Server: `1.0.0.20221015`

### Configuration

```yaml
None
```

### System information

- Operating system: `Linux`
- Browser: `Chrome`

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue
