### ISSUE TITLE
🐛 [Bug] antlr4-runtime 4.12.0 not support jdk1.8

### ISSUE THREAD

**Issue by yuhan0501** [EdurtIO/incubator-datacap#730]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/devlive-community/datacap/blob/dev/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Affected Module

Core (Default)

### Description

antlr4-runtime 4.12.0 is built by JDK 11.  It can  not work in jdk 1.8.

### Package versions

- Java: `java --version`
- Node: `node --version`
- Npm: `npm -v`
- Server: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`

### System information

Code issuse

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
We will no longer support jdk 1.8, please use a higher version to compile antlr4
