### ISSUE TITLE
🐛 [Bug] Too much text in the chat dialog box leads to confusing styles

### ISSUE THREAD

**Issue by devlivecommunity** [EdurtIO/incubator-datacap#758]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/devlive-community/datacap/blob/dev/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Affected Module

Core (Default)

### Description

Too much text in the chat dialog box leads to confusing styles

![image](https://github.com/devlive-community/datacap/assets/152371679/046414c3-b375-4fc4-a2a2-6bc14045df95)

### Package versions

- Java: `java --version`
- Node: `node --version`
- Npm: `npm -v`
- Server: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`

### System information

- Operating system: ...
- Browser: ...

**Comment by qianmoQ** [comment]
Fixed
