### ISSUE TITLE
Support Oracle

### ISSUE THREAD

**Issue by tianjinzhongqiruanjian** [EdurtIO/incubator-datacap#96]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Support Oracle

### Use Cases

Support Oracle

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue
